version: '3.1'

services:
  db:
    image: postgres:9.6.23
    restart: always
    env_file:
      - ./.env
    ports:
      - 5433:5432
      # 원래는 5432번 포트에서 열리지만, 나는 5433번을 사용하겠다는 의미
    volumes:
      - ./db_data:/var/lib/postgresql/data
      # 볼륨 마운트
      # 도커 서버가 손상되었을때를 위한 복구용 데이터가 저장되는 경로
